import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:http/http.dart' as http;
import 'package:location_based_social_app/exception/http_exception.dart';
import 'package:location_based_social_app/util/config.dart';

/// util to post image to aws s3
/// each image has two urls one for post (could expire) one for get
/// we use this util to get the url for post and post to aws S3

enum S3Folder {
  POST_IMAGE,
  USER_AVATAR
}

const FOLDER_MAP = {S3Folder.POST_IMAGE: 'post_image', S3Folder.USER_AVATAR: 'user_avatar'};

class S3Url {
  final String _uploadUrl;
  final String _downloadUrl;

  S3Url(this._uploadUrl, this._downloadUrl);

  String get uploadUrl {
    return _uploadUrl;
  }

  String get downloadUrl {
    return _downloadUrl;
  }
}

class ImageUploadUtil {

  static const Map<String, String> requestHeader = {
    'Content-type': 'application/json',
  };

  /// call service to get the url generated by S3, meanwhile service will store the get image url to db
  static Future<S3Url> getS3Urls(String token, S3Folder s3folder) async {
    final String url = '$SERVICE_DOMAIN/generatePresignedUrl';

    try {
      final res = await http.post(
        Uri.parse(url),
        headers: {...requestHeader, 'Authorization': 'Bearer $token'},
        body: json.encode({
          'fileType': '.jpg',
          'folder': FOLDER_MAP[s3folder]
        })
      );

      final responseData = json.decode(res.body) as Map<String, dynamic>;;

      if (!(responseData['success'] as bool)) {
        throw HttpException(responseData['message'] as String);
      }

      return S3Url(responseData['uploadUrl'] as String, responseData['downloadUrl'] as String);

    } catch (error) {
      rethrow;
    }
  }

  /// store image on S3
  static Future<void> uploadToS3(String url, File image) async {
    try {
      final Uint8List bytes = await image.readAsBytes();
      final response = await http.put(Uri.parse(url), body: bytes);

      if (response.statusCode != 200) {
        throw HttpException('Failed to upload image');
      }
    } catch (error) {
      rethrow;
    }
  }
}